apiVersion: v1
kind: Service
metadata:
  name: forza-api
  labels:
    app.kubernetes.io/name: forza-api
    app.kubernetes.io/instance: last-mile-top-performers
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: forza-last-mile-top-performers
    forza.tech/standard-version: v2.1
    forza.tech/team: delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: forza-api
    app.kubernetes.io/instance: last-mile-top-performers
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: forza-frontend
  labels:
    app.kubernetes.io/name: forza-frontend
    app.kubernetes.io/instance: last-mile-top-performers
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: forza-last-mile-top-performers
    forza.tech/standard-version: v2.1
    forza.tech/team: delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: forza-frontend
    app.kubernetes.io/instance: last-mile-top-performers
  ports:
    - name: http
      port: 80
      targetPort: 80
