apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: forza
  labels:
    app.kubernetes.io/name: ghcr-pull-secret
    app.kubernetes.io/instance: last-mile-top-performers
    app.kubernetes.io/component: registry-auth
    app.kubernetes.io/part-of: forza-last-mile-top-performers
    app.kubernetes.io/managed-by: kubectl
    forza.tech/standard-version: v2.1
    forza.tech/team: delivery
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<GHCR_USERNAME>",
          "password": "<GHCR_TOKEN>",
          "email": "<GHCR_EMAIL>",
          "auth": "<BASE64_OF_USERNAME_COLON_TOKEN>"
        }
      }
    }
