// <auto-generated />
using System;
using Forza.LastMile.TopPerformers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forza.LastMile.TopPerformers.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701033300_InitRepartidor")]
    partial class InitRepartidor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forza.LastMile.TopPerformers.Domain.Entities.RepartidorRendimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EntregasCompletadas")
                        .HasColumnType("integer")
                        .HasColumnName("entregas_completadas");

                    b.Property<string>("IncidenciaDescripcion")
                        .HasColumnType("text")
                        .HasColumnName("incidencia_descripcion");

                    b.Property<bool>("IsMetaAjustada")
                        .HasColumnType("boolean")
                        .HasColumnName("is_meta_ajustada");

                    b.Property<string>("MesPeriodo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mes_periodo");

                    b.Property<int>("MetaDiariaActual")
                        .HasColumnType("integer")
                        .HasColumnName("meta_diaria_actual");

                    b.Property<int>("MetaDiariaOriginal")
                        .HasColumnType("integer")
                        .HasColumnName("meta_diaria_original");

                    b.Property<string>("NombreRepartidor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_repartidor");

                    b.Property<decimal>("SatisfaccionScore")
                        .HasColumnType("numeric")
                        .HasColumnName("satisfaccion_score");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_vehiculo");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id")
                        .HasName("p_k_repartidores_rendimiento");

                    b.ToTable("repartidores_rendimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
